apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-service
  template:
    metadata:
      labels:
        app: energy-service
    spec:
      containers:
      - name: energy-service
        image: energy-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: energy-service
spec:
  selector:
    app: energy-service
  ports:
  - port: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: water-service
  template:
    metadata:
      labels:
        app: water-service
    spec:
      containers:
      - name: water-service
        image: water-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: water-service
spec:
  selector:
    app: water-service
  ports:
  - port: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: gateway-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
  - port: 8080
    nodePort: 30080
